pipeline {
    agent { label 'docker' } // agent
    options {
        timestamps()
    } // options
    stages{
        stage('test project') {
            steps {
                script {
                    withEnv(["path+sonar=${tool(name: 'SonarQube Scanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation')}"]) {
                        withSonarQubeEnv(credentialsId: 'sonarqube-wtf') {
                            sh 'bash -x .build/scanner.sh'
                        } // withSonarQubeEnv
                    } // withEnv
                } // script
            } // steps
        } // stage - test project
        stage("Quality Gate") {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                } // timeout
            } // steps
        } // stage
    } // stages
    post {
        always {
            cleanWs deleteDirs: true, notFailBuild: true
        } // always
    } // post
} // pipeline